"""Versioned specialist skill definitions — draft-only, no execution."""

from __future__ import annotations

from app.schemas.contracts import (
    KnowledgeDomain,
    SpecialistSkillCode,
    SpecialistSkillDefinition,
    SpecialistSkillExecutionPolicy,
    SpecialistSkillStatus,
)


def _skill(
    *,
    code: SpecialistSkillCode,
    title: str,
    domain: KnowledgeDomain,
    roles: list[str],
    description: str,
    inputs: list[str],
    outputs: list[str],
    clarifications: list[str],
    knowledge_scopes: list[str],
    quality_gates: list[str],
    required_tools: list[str] | None = None,
    optional_tools: list[str] | None = None,
    prerequisites: list[str] | None = None,
) -> SpecialistSkillDefinition:
    return SpecialistSkillDefinition(
        id=f"skill.{code.value}.v1",
        code=code,
        version="1.0",
        title=title,
        domain=domain,
        description=description,
        specialist_roles=roles,
        input_schema=inputs,
        output_schema=outputs,
        prerequisites=prerequisites or [],
        clarification_schema=clarifications,
        knowledge_scopes=knowledge_scopes,
        required_tools=required_tools or [],
        optional_tools=optional_tools or ["knowledge_search"],
        quality_gates=quality_gates,
        execution_policy=SpecialistSkillExecutionPolicy.DRAFT_ONLY,
        status=SpecialistSkillStatus.DRAFT,
        supersedes_version=None,
    )


def _definitions() -> list[SpecialistSkillDefinition]:
    return [
        _skill(
            code=SpecialistSkillCode.CONTENT_TELEGRAM_POST,
            title="Telegram post draft",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_specialist"],
            description="Draft Telegram post with hooks and CTA — draft only.",
            inputs=["topic", "audience", "objective", "tone", "constraints"],
            outputs=["post", "hooks", "CTA"],
            clarifications=[
                "topic",
                "audience",
                "objective",
            ],
            knowledge_scopes=[
                "constitutional",
                "content_methodology",
                "content_templates",
                "owner_brand",
                "project_brief",
            ],
            quality_gates=["no_fake_facts", "platform_fit", "brand_voice"],
        ),
        _skill(
            code=SpecialistSkillCode.CONTENT_CLAIM_VERIFICATION,
            title="Content claim verification (internal)",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_specialist"],
            description="Internal governed claim register — not a user-facing product skill.",
            inputs=["draft", "knowledge_refs", "factuality_mode"],
            outputs=["claims", "actions"],
            clarifications=[],
            knowledge_scopes=["constitutional", "content_methodology"],
            quality_gates=["no_fake_facts"],
        ),
        _skill(
            code=SpecialistSkillCode.CONTENT_EDITORIAL_REVIEW,
            title="Content editorial review (internal)",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_specialist"],
            description="Internal editorial review — not a user-facing product skill.",
            inputs=["draft", "domain", "audience"],
            outputs=["editorial_issues", "dimension_scores"],
            clarifications=[],
            knowledge_scopes=["constitutional", "content_methodology"],
            quality_gates=["platform_fit", "brand_voice"],
        ),
        _skill(
            code=SpecialistSkillCode.CONTENT_SOCIAL_POST,
            title="Social media post draft",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_specialist"],
            description="Draft social post for a named platform — draft only.",
            inputs=["platform", "topic", "audience", "objective", "tone"],
            outputs=["post", "hooks", "CTA", "hashtag_suggestions"],
            clarifications=[
                "platform",
                "topic",
                "audience",
                "objective",
                "tone",
                "length",
                "CTA",
                "brand_constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "content_methodology",
                "owner_brand",
                "project_brief",
            ],
            quality_gates=["no_fake_facts", "platform_fit", "brand_voice"],
        ),
        _skill(
            code=SpecialistSkillCode.CONTENT_CONTENT_PLAN,
            title="Content plan draft",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_planner", "content_specialist"],
            description="Structured content plan for a channel/period — draft only.",
            inputs=["channel", "period", "audience", "objectives", "themes"],
            outputs=["plan_items", "cadence", "themes", "cta_map"],
            clarifications=[
                "channel",
                "period",
                "audience",
                "objectives",
                "content_pillars",
                "constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "content_methodology",
                "content_plan_template",
                "project_brief",
            ],
            quality_gates=["no_fake_facts", "plan_completeness", "brand_voice"],
        ),
        _skill(
            code=SpecialistSkillCode.CONTENT_YOUTUBE_SCRIPT,
            title="YouTube script draft",
            domain=KnowledgeDomain.CONTENT,
            roles=["content_specialist"],
            description="YouTube script outline and spoken draft — draft only.",
            inputs=["topic", "audience", "objective", "length_minutes", "tone"],
            outputs=["hook", "outline", "script", "cta", "thumbnail_notes"],
            clarifications=[
                "topic",
                "audience",
                "objective",
                "length_minutes",
                "tone",
                "CTA",
                "brand_constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "content_methodology",
                "youtube_templates",
                "project_brief",
            ],
            quality_gates=["no_fake_facts", "platform_fit", "brand_voice"],
        ),
        _skill(
            code=SpecialistSkillCode.DESIGN_IMAGE_GENERATION,
            title="Image generation",
            domain=KnowledgeDomain.CONTENT,
            roles=["visual_specialist"],
            description="Generate an image from a prompt — explicit request only, no publication.",
            inputs=[
                "prompt",
                "aspect_ratio",
                "style",
                "realism",
                "number_of_variants",
                "text_overlay",
                "brand_constraints",
                "safety_constraints",
            ],
            outputs=[
                "generated_asset_refs",
                "generation_metadata",
                "prompt_summary",
                "warnings",
                "status",
            ],
            clarifications=[
                "aspect_ratio_when_banner",
                "text_overlay_when_banner",
                "brand_style_when_logo",
            ],
            knowledge_scopes=["constitutional", "content_quality"],
            quality_gates=["safety", "no_publication", "owner_isolation"],
            required_tools=["image_generation"],
            optional_tools=[],
        ),
        _skill(
            code=SpecialistSkillCode.RESEARCH_MARKET_OVERVIEW,
            title="Market overview research",
            domain=KnowledgeDomain.RESEARCH,
            roles=["researcher"],
            description="Structured market overview with citations — draft only.",
            inputs=["market", "geography", "objective", "constraints"],
            outputs=["overview", "segments", "risks", "evidence_links", "gaps"],
            clarifications=[
                "market",
                "geography",
                "objective",
                "time_horizon",
                "known_competitors",
                "constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "research_methodology",
                "research_templates",
                "project_sources",
                "project_evidence",
            ],
            quality_gates=["citation_required", "no_fake_facts", "insufficient_data_when_gap"],
            required_tools=[],
            optional_tools=["knowledge_search", "source_lookup"],
        ),
        _skill(
            code=SpecialistSkillCode.RESEARCH_COMPETITOR_ANALYSIS,
            title="Competitor analysis",
            domain=KnowledgeDomain.RESEARCH,
            roles=["researcher"],
            description="Competitor cards with evidence linkage — draft only.",
            inputs=["competitors", "comparison_axes", "market", "objective"],
            outputs=["competitor_cards", "comparison_matrix", "evidence_links", "gaps"],
            clarifications=[
                "competitors",
                "market",
                "comparison_axes",
                "objective",
                "geography",
            ],
            knowledge_scopes=[
                "constitutional",
                "research_methodology",
                "project_sources",
                "project_evidence",
            ],
            quality_gates=["citation_required", "no_fake_facts", "insufficient_data_when_gap"],
            optional_tools=["knowledge_search", "source_lookup"],
        ),
        _skill(
            code=SpecialistSkillCode.RESEARCH_AUDIENCE_SEGMENTATION,
            title="Audience segmentation",
            domain=KnowledgeDomain.RESEARCH,
            roles=["researcher"],
            description="Audience segments with JTBD framing — draft only.",
            inputs=["product", "market", "known_audiences", "objective"],
            outputs=["segments", "jobs_to_be_done", "messaging_hints", "gaps"],
            clarifications=[
                "product",
                "market",
                "known_audiences",
                "objective",
                "geography",
            ],
            knowledge_scopes=[
                "constitutional",
                "research_methodology",
                "audience_methodology",
                "project_brief",
            ],
            quality_gates=["citation_required", "no_fake_facts", "insufficient_data_when_gap"],
        ),
        _skill(
            code=SpecialistSkillCode.PROGRAMMER_TELEGRAM_BOT_SPEC,
            title="Telegram bot specification",
            domain=KnowledgeDomain.PROGRAMMER,
            roles=["programmer"],
            description="Specification for a Telegram bot — no deploy/shell.",
            inputs=[
                "business_purpose",
                "users",
                "primary_flows",
                "integrations",
                "admin_needs",
                "hosting_expectations",
                "constraints",
            ],
            outputs=["spec", "flows", "integrations", "non_goals", "open_questions"],
            clarifications=[
                "business_purpose",
                "users",
                "primary_flows",
                "integrations",
                "administrator_needs",
                "hosting_expectations",
                "constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "programmer_methodology",
                "telegram_bot_spec_template",
                "project_brief",
            ],
            quality_gates=["spec_completeness", "no_deploy", "no_fake_integrations"],
            required_tools=[],
            optional_tools=["knowledge_search"],
        ),
        _skill(
            code=SpecialistSkillCode.PROGRAMMER_WEBSITE_SPEC,
            title="Website specification",
            domain=KnowledgeDomain.PROGRAMMER,
            roles=["programmer"],
            description="Landing/site requirements specification — no deploy.",
            inputs=["site_type", "business_purpose", "pages", "integrations", "constraints"],
            outputs=["spec", "sitemap", "page_requirements", "non_goals", "open_questions"],
            clarifications=[
                "site_type",
                "business_purpose",
                "primary_pages",
                "integrations",
                "hosting_expectations",
                "constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "programmer_methodology",
                "website_spec_template",
                "project_brief",
            ],
            quality_gates=["spec_completeness", "no_deploy", "no_fake_integrations"],
        ),
        _skill(
            code=SpecialistSkillCode.PROGRAMMER_AUTOMATION_SPEC,
            title="Automation specification",
            domain=KnowledgeDomain.PROGRAMMER,
            roles=["programmer"],
            description="Automation/integration specification — no live wiring.",
            inputs=["business_purpose", "triggers", "systems", "data_flows", "constraints"],
            outputs=["spec", "flow_diagram_notes", "systems", "non_goals", "open_questions"],
            clarifications=[
                "business_purpose",
                "triggers",
                "systems",
                "data_flows",
                "success_criteria",
                "constraints",
            ],
            knowledge_scopes=[
                "constitutional",
                "programmer_methodology",
                "automation_spec_template",
                "project_brief",
            ],
            quality_gates=["spec_completeness", "no_deploy", "no_fake_integrations"],
        ),
        _skill(
            code=SpecialistSkillCode.STRATEGY_POSITIONING,
            title="Positioning strategy",
            domain=KnowledgeDomain.STRATEGY,
            roles=["strategist"],
            description="Positioning draft when domain eligibility is met — draft only.",
            inputs=["offer", "audience", "competitors", "differentiators"],
            outputs=["positioning", "value_props", "proof_points", "risks"],
            clarifications=[
                "offer",
                "audience",
                "competitors",
                "differentiators",
                "business_goal",
            ],
            knowledge_scopes=[
                "constitutional",
                "strategy_methodology",
                "project_brief",
                "project_evidence",
            ],
            quality_gates=["citation_required", "no_fake_facts", "domain_eligibility"],
            prerequisites=["domain_eligibility_satisfied"],
        ),
        _skill(
            code=SpecialistSkillCode.STRATEGY_OFFER_DESIGN,
            title="Offer design",
            domain=KnowledgeDomain.STRATEGY,
            roles=["strategist"],
            description="Offer packaging draft — draft only.",
            inputs=["offer", "audience", "price_context", "objections"],
            outputs=["offer_structure", "justification", "cta", "risks"],
            clarifications=[
                "offer",
                "audience",
                "price_context",
                "objections",
                "business_goal",
            ],
            knowledge_scopes=[
                "constitutional",
                "strategy_methodology",
                "offer_methodology",
                "project_brief",
            ],
            quality_gates=["citation_required", "no_fake_facts", "domain_eligibility"],
            prerequisites=["domain_eligibility_satisfied"],
        ),
        _skill(
            code=SpecialistSkillCode.STRATEGY_CHANNEL_SELECTION,
            title="Channel selection",
            domain=KnowledgeDomain.STRATEGY,
            roles=["strategist"],
            description="Channel mix recommendation — draft only.",
            inputs=["audience", "offer", "budget_band", "objectives"],
            outputs=["channels", "rationale", "sequencing", "risks"],
            clarifications=[
                "audience",
                "offer",
                "budget_band",
                "objectives",
                "geography",
            ],
            knowledge_scopes=[
                "constitutional",
                "strategy_methodology",
                "project_brief",
            ],
            quality_gates=["citation_required", "no_fake_facts", "domain_eligibility"],
            prerequisites=["domain_eligibility_satisfied"],
        ),
    ]


_BY_CODE: dict[SpecialistSkillCode, SpecialistSkillDefinition] | None = None


def _index() -> dict[SpecialistSkillCode, SpecialistSkillDefinition]:
    global _BY_CODE
    if _BY_CODE is None:
        _BY_CODE = {item.code: item for item in _definitions()}
    return _BY_CODE


def list_skills() -> list[SpecialistSkillDefinition]:
    return list(_index().values())


def get_skill(code: SpecialistSkillCode | str) -> SpecialistSkillDefinition | None:
    if isinstance(code, str):
        try:
            code = SpecialistSkillCode(code)
        except ValueError:
            return None
    return _index().get(code)
