"""Connector Gateway interface layer (SKILL-01.5).

Governing wrapper for external I/O. Existing provider adapters under ``app/mcp/``
and ``app/business_tools/`` are preserved; this module defines contracts and policy
only — no real connector invocation in this phase.
"""

from app.connectors.adapters import (
    ConnectorAdapterProtocol,
    ProductionConnectorAdapterStub,
    SyntheticConnectorAdapter,
)
from app.connectors.classifications import (
    is_read_only_no_side_effect,
    requires_elevated_approval,
    requires_human_approval,
)
from app.connectors.contracts import (
    BudgetPolicy,
    ConnectorActionType,
    ConnectorApprovalClass,
    ConnectorClass,
    ConnectorCostEstimate,
    ConnectorDataSensitivity,
    ConnectorDescriptor,
    ConnectorEvidenceDescriptor,
    ConnectorExecutionError,
    ConnectorExecutionRequest,
    ConnectorExecutionResult,
    ConnectorExecutionResultStatus,
    ConnectorHealthState,
    ConnectorIdempotencyClass,
    ConnectorPolicyDecision,
    ConnectorPolicyFinding,
    ConnectorPolicyOutcome,
    ConnectorSideEffectClass,
    ConnectorStatus,
    ConnectorToolDefinition,
    CredentialBindingReference,
    ProjectConnectorBinding,
    RetryPolicy,
    TenantConnectorBinding,
    TimeoutPolicy,
    payload_contains_secret_like_keys,
    validate_connector_status,
)
from app.connectors.errors import (
    ConnectorAdapterUnavailableError,
    ConnectorApprovalRequiredError,
    ConnectorBudgetPolicyError,
    ConnectorCredentialBindingError,
    ConnectorError,
    ConnectorEvidenceRequirementError,
    ConnectorExecutionNormalizationError,
    ConnectorIdempotencyError,
    ConnectorNotFoundError,
    ConnectorPolicyDeniedError,
    ConnectorRatePolicyError,
    ConnectorTenantVisibilityError,
    ConnectorToolNotFoundError,
    ConnectorVersionNotFoundError,
)
from app.connectors.evidence import (
    build_evidence_descriptor,
    hash_payload,
    redact_provider_metadata,
)
from app.connectors.gateway import ConnectorGateway, build_test_gateway
from app.connectors.policies import evaluate_connector_request, skill_tool_intersection_allowed

__all__ = [
    "BudgetPolicy",
    "ConnectorActionType",
    "ConnectorAdapterProtocol",
    "ConnectorAdapterUnavailableError",
    "ConnectorApprovalClass",
    "ConnectorApprovalRequiredError",
    "ConnectorBudgetPolicyError",
    "ConnectorClass",
    "ConnectorCostEstimate",
    "ConnectorCredentialBindingError",
    "ConnectorDataSensitivity",
    "ConnectorDescriptor",
    "ConnectorError",
    "ConnectorEvidenceDescriptor",
    "ConnectorEvidenceRequirementError",
    "ConnectorExecutionError",
    "ConnectorExecutionNormalizationError",
    "ConnectorExecutionRequest",
    "ConnectorExecutionResult",
    "ConnectorExecutionResultStatus",
    "ConnectorGateway",
    "ConnectorHealthState",
    "ConnectorIdempotencyClass",
    "ConnectorIdempotencyError",
    "ConnectorNotFoundError",
    "ConnectorPolicyDecision",
    "ConnectorPolicyDeniedError",
    "ConnectorPolicyFinding",
    "ConnectorPolicyOutcome",
    "ConnectorRatePolicyError",
    "ConnectorSideEffectClass",
    "ConnectorStatus",
    "ConnectorTenantVisibilityError",
    "ConnectorToolDefinition",
    "ConnectorToolNotFoundError",
    "ConnectorVersionNotFoundError",
    "CredentialBindingReference",
    "ProductionConnectorAdapterStub",
    "ProjectConnectorBinding",
    "RetryPolicy",
    "SyntheticConnectorAdapter",
    "TenantConnectorBinding",
    "TimeoutPolicy",
    "build_evidence_descriptor",
    "build_test_gateway",
    "evaluate_connector_request",
    "hash_payload",
    "is_read_only_no_side_effect",
    "payload_contains_secret_like_keys",
    "redact_provider_metadata",
    "requires_elevated_approval",
    "requires_human_approval",
    "skill_tool_intersection_allowed",
    "validate_connector_status",
]
