/**
 * Canonical product capability registry — single SoT for IA execution (PRODUCT-01.5).
 */

import type { ProductCapability } from "./contracts";

export const PRODUCT_CAPABILITY_REGISTRY: readonly ProductCapability[] = [
  // ── Workspace ──────────────────────────────────────────────────────────────
  {
    id: "workspace.home",
    canonicalName: "Workspace Home",
    labelKey: "nav.home",
    parentId: undefined,
    category: "workspace",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    route: "/workspace",
    entryAction: "route",
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    ownerApproved: true,
    journeyIds: ["J1.2"],
    iaScreenIds: ["home"],
    navExact: true,
  },
  {
    id: "workspace.projects",
    canonicalName: "Projects",
    labelKey: "nav.projects",
    parentId: undefined,
    category: "workspace",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    route: "/workspace/projects",
    entryAction: "route",
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    ownerApproved: true,
    journeyIds: ["J1.5"],
    iaScreenIds: ["projects.index"],
  },
  {
    id: "workspace.analytics",
    canonicalName: "Analytics",
    labelKey: "capability.analytics",
    descriptionKey: "capability.analytics.description",
    parentId: undefined,
    category: "workspace",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J9.1"],
    iaScreenIds: ["analytics.dashboard"],
  },
  {
    id: "workspace.knowledge",
    canonicalName: "Knowledge",
    labelKey: "capability.knowledge",
    parentId: undefined,
    category: "workspace",
    surfaceClass: "INTERNAL_ONLY",
    availability: "internal",
    route: "/workspace/knowledge",
    entryAction: "route",
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: false,
    developerVisible: true,
    reserved: true,
    journeyIds: ["J10.2"],
    iaScreenIds: ["knowledge.index"],
  },

  // ── Project stages ─────────────────────────────────────────────────────────
  {
    id: "project.intake",
    canonicalName: "Project Intake",
    labelKey: "capability.intake",
    parentId: "workspace.projects",
    category: "project",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    route: "/workspace/projects/new",
    entryAction: "route",
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    ownerApproved: true,
    homeIntentId: "validate-idea",
    journeyIds: ["J1.4"],
    iaScreenIds: ["intake.wizard"],
  },
  {
    id: "project.research",
    canonicalName: "Research",
    labelKey: "capability.research",
    parentId: "workspace.projects",
    category: "project",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    entryAction: "panel",
    requiresProject: true,
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    ownerApproved: true,
    journeyIds: ["J2.1", "J2.2", "J2.3", "J2.4", "J2.5"],
    iaScreenIds: ["research.panel", "home.project"],
  },
  {
    id: "project.strategy",
    canonicalName: "Strategy",
    labelKey: "capability.strategy",
    parentId: "workspace.projects",
    category: "project",
    surfaceClass: "RESERVED",
    availability: "planned",
    entryAction: "panel",
    requiresProject: true,
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J4.1", "J4.2"],
    iaScreenIds: ["strategy.panel"],
  },
  {
    id: "project.launch",
    canonicalName: "Launch",
    labelKey: "capability.launch",
    parentId: "workspace.projects",
    category: "project",
    surfaceClass: "RESERVED",
    availability: "planned",
    entryAction: "panel",
    requiresProject: true,
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J5.1", "J5.2", "J5.3"],
    iaScreenIds: ["launch.panel"],
  },
  {
    id: "launch.content",
    canonicalName: "Content",
    labelKey: "capability.content",
    parentId: "project.launch",
    category: "launch",
    surfaceClass: "INTERNAL_ONLY",
    availability: "available",
    entryAction: "panel",
    requiresProject: true,
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: true,
    reserved: false,
    journeyIds: ["J6.1", "J6.2", "J6.3"],
    iaScreenIds: ["content.review"],
  },
  {
    id: "project.content_director",
    canonicalName: "Project Content",
    labelKey: "contentDirector.navLabel",
    descriptionKey: "contentDirector.subtitle",
    parentId: "workspace.projects",
    category: "project",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    route: "/workspace?view=content_director",
    entryAction: "route",
    requiresProject: true,
    allowedRoles: ["owner", "manager"],
    // Reachable inside Project Command Center — not a top-level Home/nav product.
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    // Registry activation for Text/Image paths — not product slice owner_accepted.
    ownerApproved: true,
    journeyIds: ["J6.1", "J6.2"],
    iaScreenIds: ["content.review"],
  },
  {
    id: "launch.visuals",
    canonicalName: "Visuals",
    labelKey: "capability.visuals",
    parentId: "project.launch",
    category: "launch",
    surfaceClass: "RESERVED",
    availability: "planned",
    entryAction: "panel",
    requiresProject: true,
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J7.1", "J7.2"],
    iaScreenIds: ["visuals.panel"],
  },
  {
    id: "launch.publication",
    canonicalName: "Publication",
    labelKey: "capability.publication",
    parentId: "project.launch",
    category: "launch",
    surfaceClass: "RESERVED",
    availability: "planned",
    entryAction: "route",
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J8.1"],
    iaScreenIds: ["publication.channels"],
  },

  // ── Settings ───────────────────────────────────────────────────────────────
  {
    id: "settings.general",
    canonicalName: "Settings",
    labelKey: "nav.settings",
    parentId: undefined,
    category: "settings",
    surfaceClass: "CANONICAL_PUBLIC",
    availability: "available",
    route: "/workspace/settings",
    entryAction: "route",
    allowedRoles: ["owner", "manager", "employee", "team_member"],
    publicVisible: true,
    developerVisible: true,
    reserved: false,
    ownerApproved: true,
    journeyIds: ["J11.1"],
    iaScreenIds: ["settings.root"],
  },
  {
    id: "settings.billing",
    canonicalName: "Billing",
    labelKey: "capability.billing",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J11.2"],
    iaScreenIds: ["settings.billing"],
  },
  {
    id: "settings.team",
    canonicalName: "Team",
    labelKey: "capability.team",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: ["J11.3"],
    iaScreenIds: ["settings.team"],
  },
  {
    id: "settings.hr",
    canonicalName: "HR",
    labelKey: "capability.hr",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: [],
    iaScreenIds: ["settings.hr"],
  },
  {
    id: "settings.legal",
    canonicalName: "Legal",
    labelKey: "capability.legal",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: [],
    iaScreenIds: ["settings.legal"],
  },
  {
    id: "settings.programmer",
    canonicalName: "Programmer",
    labelKey: "capability.programmer",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: [],
    iaScreenIds: ["settings.programmer"],
  },
  {
    id: "settings.finance",
    canonicalName: "Finance",
    labelKey: "capability.finance",
    parentId: "settings.general",
    category: "settings",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: [],
    iaScreenIds: ["settings.finance"],
  },
  {
    id: "settings.crm",
    canonicalName: "CRM",
    labelKey: "capability.crm",
    parentId: undefined,
    category: "workspace",
    surfaceClass: "RESERVED",
    availability: "reserved",
    entryAction: "route",
    allowedRoles: ["owner", "manager"],
    publicVisible: false,
    developerVisible: false,
    reserved: true,
    journeyIds: [],
    iaScreenIds: ["crm.index"],
  },

  // ── Internal developer surfaces ────────────────────────────────────────────
  {
    id: "internal.review",
    canonicalName: "Review Queue",
    labelKey: "nav.reviewQueue",
    parentId: "launch.content",
    category: "launch",
    surfaceClass: "INTERNAL_ONLY",
    availability: "internal",
    route: "/workspace/review",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: true,
    reserved: false,
    journeyIds: ["J6.2"],
    iaScreenIds: ["content.review"],
  },
  {
    id: "internal.assistant",
    canonicalName: "AI Assistant",
    labelKey: "nav.aiAssistant",
    parentId: "workspace.home",
    category: "workspace",
    surfaceClass: "INTERNAL_ONLY",
    availability: "internal",
    route: "/workspace/assistant",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: true,
    reserved: false,
    journeyIds: ["J1.3"],
    iaScreenIds: ["assistant.index"],
  },
  {
    id: "internal.channels",
    canonicalName: "Channels",
    labelKey: "nav.channels",
    parentId: "launch.publication",
    category: "launch",
    surfaceClass: "INTERNAL_ONLY",
    availability: "internal",
    route: "/workspace/channels",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: true,
    reserved: false,
    journeyIds: ["J8.1"],
    iaScreenIds: ["publication.channels"],
  },
  {
    id: "internal.assets",
    canonicalName: "Materials Library",
    labelKey: "nav.materials",
    parentId: "launch.content",
    category: "launch",
    surfaceClass: "INTERNAL_ONLY",
    availability: "internal",
    route: "/workspace/assets",
    entryAction: "route",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: true,
    reserved: false,
    journeyIds: ["J6.3"],
    iaScreenIds: ["assets.index"],
  },

  // ── Legacy redirects (compatibility) ───────────────────────────────────────
  {
    id: "legacy.tasks",
    canonicalName: "Legacy Tasks",
    labelKey: "capability.legacy.tasks",
    category: "workspace",
    surfaceClass: "REDIRECT",
    availability: "disabled",
    route: "/workspace/tasks",
    redirectTarget: "/workspace",
    entryAction: "redirect",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: false,
    journeyIds: [],
    iaScreenIds: [],
  },
  {
    id: "legacy.research",
    canonicalName: "Legacy Research Route",
    labelKey: "capability.legacy.research",
    category: "workspace",
    surfaceClass: "REDIRECT",
    availability: "disabled",
    route: "/workspace/research",
    redirectTarget: "/workspace",
    entryAction: "redirect",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: false,
    journeyIds: [],
    iaScreenIds: [],
  },
  {
    id: "legacy.execution",
    canonicalName: "Legacy Execution Route",
    labelKey: "capability.legacy.execution",
    category: "workspace",
    surfaceClass: "REDIRECT",
    availability: "disabled",
    route: "/workspace/execution",
    redirectTarget: "/workspace",
    entryAction: "redirect",
    allowedRoles: ["owner"],
    publicVisible: false,
    developerVisible: false,
    reserved: false,
    journeyIds: [],
    iaScreenIds: [],
  },
] as const;
