"""H2.8E — identity recipes (configuration, not new product skills)."""

from __future__ import annotations

from app.schemas.contracts import (
    IdentityProductMode,
    IdentityProviderCapability,
    IdentityRecipe,
    IdentityRecipeCode,
)


def list_identity_recipes() -> list[IdentityRecipe]:
    return [
        IdentityRecipe(
            code=IdentityRecipeCode.NEW_CREATIVE_CHARACTER,
            title="New creative character",
            title_ru="Новый креативный персонаж",
            required_inputs=["prompt"],
            provider_capability_required=None,
            approval_required=False,
            tool_profile="design.image_generation",
            quality_gate="none",
            review_required=False,
            prohibited_fallbacks=[],
            product_mode=IdentityProductMode.CREATIVE_GENERATION,
            notes="No identity guarantee.",
        ),
        IdentityRecipe(
            code=IdentityRecipeCode.PRESERVE_PERSON_NEW_SCENE,
            title="Preserve a person in a new scene",
            title_ru="Сохранить человека в новой сцене",
            required_inputs=["prompt", "reference_set", "primary_face", "consent"],
            provider_capability_required=IdentityProviderCapability.CONDITIONALLY_SUITABLE,
            approval_required=True,
            tool_profile="design.image_generation",
            quality_gate="visual_consistency",
            review_required=True,
            prohibited_fallbacks=["silent_text_to_image", "gptunnel_with_refs"],
            product_mode=IdentityProductMode.PERSON_IDENTITY_PRESERVATION,
            notes="Requires qualified capable provider + owner review.",
        ),
        IdentityRecipe(
            code=IdentityRecipeCode.APPLY_STYLE_NO_IDENTITY,
            title="Apply visual style without identity",
            title_ru="Стиль без сохранения внешности",
            required_inputs=["prompt", "style_reference_optional"],
            provider_capability_required=None,
            approval_required=False,
            tool_profile="design.image_generation",
            quality_gate="none",
            review_required=False,
            prohibited_fallbacks=["label_as_identity_preservation"],
            product_mode=IdentityProductMode.REFERENCE_GUIDED_STYLE,
            notes="Not identity preservation.",
        ),
        IdentityRecipe(
            code=IdentityRecipeCode.EXACT_LOGO_PLACEMENT,
            title="Exact logo placement",
            title_ru="Точное размещение логотипа",
            required_inputs=["logo_reference", "target_canvas"],
            provider_capability_required=None,
            approval_required=False,
            tool_profile="design.image_generation",
            quality_gate="deterministic_compositing",
            review_required=True,
            prohibited_fallbacks=["generative_redraw_logo"],
            product_mode=IdentityProductMode.EXACT_LOGO_PRODUCT_PLACEMENT,
            notes="Deterministic compositing — no generative redraw.",
        ),
        IdentityRecipe(
            code=IdentityRecipeCode.STRENGTHEN_LIKENESS,
            title="Strengthen likeness",
            title_ru="Усилить сходство",
            required_inputs=["prompt", "reference_set", "primary_face"],
            provider_capability_required=IdentityProviderCapability.CONDITIONALLY_SUITABLE,
            approval_required=True,
            tool_profile="design.image_generation",
            quality_gate="visual_consistency",
            review_required=True,
            prohibited_fallbacks=["silent_text_to_image"],
            product_mode=IdentityProductMode.PERSON_IDENTITY_PRESERVATION,
            notes="Uses strengthen_likeness / maximum fidelity — still best-effort.",
        ),
        IdentityRecipe(
            code=IdentityRecipeCode.PROVIDER_QUALIFICATION,
            title="Provider qualification",
            title_ru="Квалификация провайдера",
            required_inputs=["reference_set", "baseline_asset", "paid_approval"],
            provider_capability_required=None,
            approval_required=True,
            tool_profile="identity_qualification_operator",
            quality_gate="owner_visual_review",
            review_required=True,
            prohibited_fallbacks=["auto_mark_suitable_from_unit_tests", "four_calls_without_approval"],
            product_mode=IdentityProductMode.PERSON_IDENTITY_PRESERVATION,
            notes="Operator-driven; one diagnostic call first.",
        ),
    ]
