/** Backend ImplementationPlan DTOs (Commercial MVP P1.1). */

export type BackendImplementationPlanDto = {
  id: string;
  owner_id: string;
  project_id: string;
  marketing_strategy_id: string;
  marketing_strategy_version: number;
  business_verdict_id: string;
  business_verdict_version: number;
  evidence_snapshot_id: string;
  evidence_snapshot_hash: string;
  version: number;
  lifecycle_status: string;
  plan_origin: string;
  title: string;
  summary: string;
  implementation_horizon: string;
  workstreams: Array<Record<string, unknown>>;
  milestones: Array<Record<string, unknown>>;
  tasks: Array<Record<string, unknown>>;
  role_assignments: Array<Record<string, unknown>>;
  dependencies: Array<Record<string, unknown>>;
  deliverables: Array<Record<string, unknown>>;
  budget_plan: Record<string, unknown>;
  budget_gates: Array<Record<string, unknown>>;
  approval_gates: Array<Record<string, unknown>>;
  conditions: Array<Record<string, unknown>>;
  implementation_risks: Array<Record<string, unknown>>;
  assumptions: Array<Record<string, unknown>>;
  roadmap: Array<Record<string, unknown>>;
  readiness_status: string;
  readiness_reasons: string[];
  submitted_by: string | null;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  rejection_reason: string | null;
  block_reason: string | null;
  supersedes_plan_id: string | null;
  creates_marketing_plan: boolean;
  creates_specialist_tasks: boolean;
  creates_campaign: boolean;
  creates_execution_approval: boolean;
  creates_publication_approval: boolean;
  creates_agent_run: boolean;
  is_marketing_plan: boolean;
  budget_gates_authorize_spend: boolean;
  approval_gates_are_local_only: boolean;
  created_at: string;
  updated_at: string;
};

export type BackendImplementationHandoffPreviewDto = {
  plan_id: string;
  plan_version: number;
  eligible: boolean;
  mapped_task_count: number;
  unsupported_task_count: number;
  blocked_task_count: number;
  unsupported_roles: string[];
  dependency_loss: string[];
  acceptance_criteria_loss: string[];
  budget_gate_gaps: string[];
  approval_gate_gaps: string[];
  readiness: string;
  blockers: string[];
  creates_marketing_plan: boolean;
  creates_specialist_tasks: boolean;
  note: string;
};
