"""Skill and Connector lineage preparation layer (SKILL-01.7).

Connects package validation, quarantine, registry, connector and audit artifacts
into deterministic lineage graphs. No persistence or live runtime integration.
"""

from app.lineage.builders import (
    build_audit_lineage,
    build_connector_request_lineage,
    build_connector_result_lineage,
    build_package_validation_lineage,
    build_quarantine_lineage,
    build_registry_projection_lineage,
    build_skill_execution_lineage_descriptor,
    combine_lineage_graphs,
)
from app.lineage.contracts import (
    LINEAGE_SCHEMA_VERSION,
    AuditLineageDescriptor,
    ConnectorExecutionLineageDescriptor,
    EvidenceLineageReference,
    LineageContext,
    LineageEdge,
    LineageEdgeType,
    LineageFinding,
    LineageFindingCode,
    LineageFindingSeverity,
    LineageGraph,
    LineageNodeReference,
    LineageNodeType,
    LineageSourceReference,
    LineageValidationResult,
    SkillExecutionLineageDescriptor,
    validate_edge_type,
    validate_node_type,
)
from app.lineage.errors import (
    LineageBuildError,
    LineageContractError,
    LineageError,
    LineageMergeError,
    LineageValidationError,
)
from app.lineage.identity import (
    audit_report_node_id,
    connector_evidence_node_id,
    connector_request_node_id,
    connector_result_node_id,
    evidence_node_id,
    package_validation_node_id,
    quarantine_import_node_id,
    registry_projection_node_id,
    registry_snapshot_node_id,
    skill_package_node_id,
)
from app.lineage.mappings import (
    map_audit_evidence_to_lineage_reference,
    map_connector_evidence_to_lineage_reference,
    map_lineage_reference_to_knowledge_evidence,
    map_package_validation_to_evidence_source_reference,
    map_quarantine_provenance_to_evidence_reference,
)
from app.lineage.serialization import (
    canonical_json,
    compute_graph_hash,
    sanitize_for_serialization,
    serialize_graph,
)
from app.lineage.validators import filter_graph_for_tenant, validate_lineage_continuity

__all__ = [
    "LINEAGE_SCHEMA_VERSION",
    "AuditLineageDescriptor",
    "ConnectorExecutionLineageDescriptor",
    "EvidenceLineageReference",
    "LineageBuildError",
    "LineageContext",
    "LineageContractError",
    "LineageEdge",
    "LineageEdgeType",
    "LineageError",
    "LineageFinding",
    "LineageFindingCode",
    "LineageFindingSeverity",
    "LineageGraph",
    "LineageMergeError",
    "LineageNodeReference",
    "LineageNodeType",
    "LineageSourceReference",
    "LineageValidationError",
    "LineageValidationResult",
    "SkillExecutionLineageDescriptor",
    "audit_report_node_id",
    "build_audit_lineage",
    "build_connector_request_lineage",
    "build_connector_result_lineage",
    "build_package_validation_lineage",
    "build_quarantine_lineage",
    "build_registry_projection_lineage",
    "build_skill_execution_lineage_descriptor",
    "canonical_json",
    "combine_lineage_graphs",
    "compute_graph_hash",
    "connector_evidence_node_id",
    "connector_request_node_id",
    "connector_result_node_id",
    "evidence_node_id",
    "filter_graph_for_tenant",
    "map_audit_evidence_to_lineage_reference",
    "map_connector_evidence_to_lineage_reference",
    "map_lineage_reference_to_knowledge_evidence",
    "map_package_validation_to_evidence_source_reference",
    "map_quarantine_provenance_to_evidence_reference",
    "package_validation_node_id",
    "quarantine_import_node_id",
    "registry_projection_node_id",
    "registry_snapshot_node_id",
    "sanitize_for_serialization",
    "serialize_graph",
    "skill_package_node_id",
    "validate_edge_type",
    "validate_lineage_continuity",
    "validate_node_type",
]
